language: objective-c
osx_image: xcode10.1
script: xcodebuild -project Marklight.xcodeproj -scheme 'Marklight iOS' -destination 'platform=iOS Simulator,OS=12.1,id=B40F7090-26EE-4D2E-A7A2-C13E10EDA669' -enableCodeCoverage YES clean build test
after_success:
  - bash <(curl -s https://codecov.io/bash)


