language: objective-c
osx_image: xcode8.2
script: xcodebuild -project Marklight.xcodeproj -scheme "Marklight iOS" -destination 'platform=iOS Simulator,OS=10.2,id=E40727B3-41FB-4D6E-B4CB-BFA87109EB12' -enableCodeCoverage YES clean build test
after_success:
  - bash <(curl -s https://codecov.io/bash)


